// frontend/src/components/mentorados/HeadhuntersModal.tsx
import { useEffect, useMemo, useState } from "react"

type HH = { name: string; url: string }

const HEADHUNTERS: HH[] = [
  { name: "Lissa Schreurs", url: "https://www.linkedin.com/in/lissa-schreurs-746bb427/" },
  { name: "Larissa Marchesin", url: "https://www.linkedin.com/in/larissa-marchesin/" },
  { name: "Ezequiel Silva", url: "https://www.linkedin.com/in/ezequiel-silva/" },
  { name: "Andre Abram", url: "https://www.linkedin.com/in/andre-abram/" },
  { name: "Roberta Tenenbaum", url: "https://www.linkedin.com/in/roberta-tenenbaum-b7758312/" },
  { name: "Aldo Bergamasco", url: "https://www.linkedin.com/in/aldobergamasco/" },
  { name: "Raquel Medeiros", url: "https://www.linkedin.com/in/raquel-medeiros-1b009324/" },
  { name: "Mariane Montana", url: "https://www.linkedin.com/in/mariane-montana-a579796/" },
  { name: "Karin Karay", url: "https://www.linkedin.com/in/karin-karay-0591b2/" },
  { name: "Patricia Holland", url: "https://www.linkedin.com/in/hollandpatricia/" },
  { name: "Lúiz Arrobas", url: "https://www.linkedin.com/in/arrobas/" },
  { name: "Carla Camargo", url: "https://www.linkedin.com/in/carla-camargo-/" },
  { name: "Marcelo Leite", url: "https://www.linkedin.com/in/hrmarceloleite/" },
  { name: "Thais Mariz", url: "https://www.linkedin.com/in/thaismariz/" },
  { name: "Thais Tiemi Seguchi", url: "https://www.linkedin.com/in/tseguchi/" },
  { name: "Leticia Longhi", url: "https://www.linkedin.com/in/leticia-longhi-893636194/" },
  { name: "Humberto Branco", url: "https://www.linkedin.com/in/humberto-branco-4b02b9/" },
  { name: "Ana Paula Assunção", url: "https://www.linkedin.com/in/apassuncao/" },
  { name: "Guilherme Maciel", url: "https://www.linkedin.com/in/gmaciel10/" },
  { name: "Natasha La Marca", url: "https://www.linkedin.com/in/natasha-la-marca-93990412/" },
  { name: "Camila Tofeti", url: "https://www.linkedin.com/in/camila-tofeti-40b40a33/" },
  { name: "Mariana Xavier", url: "https://www.linkedin.com/in/mariana-xp/" },
  { name: "Henrique Valente Carneiro", url: "https://www.linkedin.com/in/henrique-carneiro/" },
  { name: "Aline Benvengo Laranjeira", url: "https://www.linkedin.com/in/aline-larangeira/" },
  { name: "Flávia Leão Fernandes", url: "https://www.linkedin.com/in/flavialeaofernandes/" },
  { name: "Jacques Sarfatti", url: "https://www.linkedin.com/in/jacques-sarfatti-b9b00429/" },
  { name: "Tiago Salomão Abrahão", url: "https://www.linkedin.com/in/tiagosalomao/" },
  { name: "Thiala Silva", url: "https://www.linkedin.com/in/thisisthiala/" },
  { name: "Higor Balmiza", url: "https://www.linkedin.com/in/higorbalmiza/" },
  { name: "Cinthia Nacarato", url: "https://www.linkedin.com/in/nacaratocinthia/" },
  { name: "Amanda P.", url: "https://www.linkedin.com/in/amanda-p-554a1b55/" },
  { name: "André Cantamessa", url: "https://www.linkedin.com/in/andr%C3%A9-cantamessa-68a7a045/" },
  { name: "Roselaine Aparecida da Silva Souza", url: "https://www.linkedin.com/in/roselainesilvasouza/" },
  { name: "Karina Pennella", url: "https://www.linkedin.com/in/karina-pennella-235b495a/" },
  { name: "Isabela Cortopassi", url: "https://www.linkedin.com/in/isabela-cortopassi/" },
  { name: "Raissa Ragazzi", url: "https://www.linkedin.com/in/raissaragazzi/" },
  { name: "Thaisa Lobel", url: "https://www.linkedin.com/in/thaisalobel/" },
  { name: "Marcus Giorgi", url: "https://www.linkedin.com/in/marcusgiorgi/" },
  { name: "Isabela Noronha", url: "https://www.linkedin.com/in/isabela-noronha-b789b818b/" },
  { name: "Chiara Mazzocato", url: "https://www.linkedin.com/in/chiara-mazzocato-9952961b3/" },
  { name: "Fernanda Gorski", url: "https://www.linkedin.com/in/fernanda-gorski/" },
  { name: "Natalia Correa Benabou", url: "https://www.linkedin.com/in/nataliabenabou/" },
  { name: "Ana Beatriz Christiani", url: "https://www.linkedin.com/in/ana-beatriz-christiani-0728091b7/" },
  { name: "Patricia Cecconi Fonte", url: "https://www.linkedin.com/in/patricia-cecconi-fontes-abb27439/" },
  { name: "Julia Roberti", url: "https://www.linkedin.com/in/julia-roberti-8614061b3/" },
  { name: "Rafael Di Maio", url: "https://www.linkedin.com/in/rafael-di-maio/" },
  { name: "João Philipe Lins", url: "https://www.linkedin.com/in/jo%C3%A3o-philipe-lins-267001a8/" },
  { name: "Carlos Ornellas", url: "https://www.linkedin.com/in/carlos-ornellas/" },
  { name: "Henrique Valle Saboya Salles", url: "https://www.linkedin.com/in/henrique-valle-saboya-salles-471643205/" },
  { name: "Daniella Stuart", url: "https://www.linkedin.com/in/daniella-stuart-76440138/" },
  { name: "Carolina Bronze", url: "https://www.linkedin.com/in/carolina-bronze-b41375101/" },
  { name: "Daniel Winograd", url: "https://www.linkedin.com/in/daniel-winograd-060000bb/" },
  { name: "Marcela Dantas de Assis", url: "https://www.linkedin.com/in/marcela-dantas-de-assis-4b432ab0/" },
  { name: "Mirian Imazava", url: "https://www.linkedin.com/in/mirianimazava/" },
  { name: "Katyanna Salvador", url: "https://www.linkedin.com/in/katyannasalvador/" },
  { name: "Ana Paula Ramos", url: "https://www.linkedin.com/in/ana-paula-ramos-a360b57/" },
  { name: "Caroline B. De Nadai", url: "https://www.linkedin.com/in/caroline-de-nadai/" },
  { name: "Daniel Rocha Rodrigues", url: "https://www.linkedin.com/in/daniel-rocha-rodrigues-headhunter/" },
  { name: "André Behs", url: "https://www.linkedin.com/in/andr%C3%A9-behs-4a264b28/" },
  { name: "Henrique Guitti", url: "https://www.linkedin.com/in/henriqueguitti/" },
  { name: "Nicolas Salvarani", url: "https://www.linkedin.com/in/nicolas-salvarani-a483689b/" },
  { name: "Brunna Baggio", url: "https://www.linkedin.com/in/brunna-baggio-a5460835/" },
  { name: "Igor Schultz", url: "https://www.linkedin.com/in/igortschultz/" },
  { name: "Marcelo Dib", url: "https://www.linkedin.com/in/marcelo-dib-612914125/" },
  { name: "Luiz Gustavo Mariano", url: "https://www.linkedin.com/in/luiz-gustavo-mariano-0676649/" },
  { name: "Rebecca Gomes", url: "https://www.linkedin.com/in/rebecca-gomes-aba42a123/" },
  { name: "Ricardo Guimaraes Gewehr", url: "https://www.linkedin.com/in/ricardo-guimaraes-gewehr/" },
  { name: "Ingrid Caetano", url: "https://www.linkedin.com/in/ingrid-caetano-137a3781/" },
  { name: "Isadora Mitteldorf", url: "https://www.linkedin.com/in/isadora-mitteldorf-2580468a/" },
  { name: "Camila Coutinho", url: "https://www.linkedin.com/in/caamilacgs/" },
  { name: "Rafael da Costa Martins", url: "https://www.linkedin.com/in/rafaeldacostamartins/" },
  { name: "Maria Teresa Boratto", url: "https://www.linkedin.com/in/maria-teresa-boratto/" },
  { name: "Bernardo Cavour", url: "https://www.linkedin.com/in/bernardo-cavour-436174/" },
  { name: "Saulo Ferreira", url: "https://www.linkedin.com/in/saulo-ferreira-5264a825/" },
  { name: "Elaine Dos Santos Rego", url: "https://www.linkedin.com" }, // link original não veio formatado
  { name: "Thiago Pimenta", url: "https://www.linkedin.com/in/thiago-pimenta-57754b22/" },
  { name: "Camila Junqueira", url: "https://www.linkedin.com/in/cjunqueira/" },
  { name: "Camila Fuzo", url: "https://www.linkedin.com/in/camilafuzo/" },
  { name: "Bruna de Santi", url: "https://www.linkedin.com/in/bruna-de-santi-2896a429a/" },
  { name: "Leandro Pedrosa", url: "https://www.linkedin.com/in/leandropedrosa/" },
  { name: "Mateus Alves", url: "https://www.linkedin.com/in/mateus-alves/" },
  { name: "Vinicius N.", url: "https://www.linkedin.com/in/viniciusnlima/" },
  { name: "Alan Seleme", url: "https://www.linkedin.com/in/alan-seleme/" },
  { name: "Alessandro (Baraldi) Baraldi", url: "https://www.linkedin.com/in/abmsearchbaraldi/" },
  { name: "Melissa Gimenez", url: "https://www.linkedin.com/in/melissa-gimenez-61178a22/" },
  { name: "Celia Aguilar Chacon", url: "https://www.linkedin.com/in/celia-aguilar-chacon-545183180/" },
  { name: "Rodrigo Byrro", url: "https://www.linkedin.com/in/rodrigobyrro/" },
  { name: "Amanda Branco", url: "https://www.linkedin.com/in/amanda-souza-branco/" },
  { name: "Leonardo Ribeiro", url: "https://www.linkedin.com/in/leonardoribeiro/" },
  { name: "Ligia Biamino", url: "https://www.linkedin.com/in/ligia-biamino-1546816/" },
  { name: "Alberto Yamada", url: "https://www.linkedin.com/in/alberto-yamada-2843589/" },
  { name: "Darcio Crespi", url: "https://www.linkedin.com/in/darcio-crespi-3b80898/" },
  { name: "Anna Maria da Costa", url: "https://www.linkedin.com/in/anna-maria-da-costa-31a12924/" },
  { name: "Larry Hartmann", url: "https://www.linkedin.com/in/larry-hartmann-723b3a/" },
  { name: "Léssel Della Manna", url: "https://www.linkedin.com/in/l%C3%A9ssel-della-manna-a1184b14/" },
  { name: "Ana Carolina Moraes Botton Zanetta", url: "https://www.linkedin.com/in/anacarolinamoraesbotton/" },
  { name: "Bruno Lino", url: "https://www.linkedin.com/in/brlino/" },
  { name: "Denys Monteiro", url: "https://www.linkedin.com/in/denys-monteiro-997100/" },
  { name: "Geraldo Teixeira", url: "https://www.linkedin.com/in/geraldo-teixeira-22482716/" },
  { name: "Deborah R.", url: "https://www.linkedin.com/in/deborahroriz/" },
  { name: "Eduardo \"Ted\" Latham", url: "https://www.linkedin.com/in/eduardo-ted-latham-4803a01/" },
  { name: "Manuela Passos", url: "https://www.linkedin.com/in/manuela-passos-640077a9/" },
  { name: "Tom Pope", url: "https://www.linkedin.com/in/tmjpope/" },
  { name: "Ashley Munday", url: "https://www.linkedin.com/in/ashleymunday0/" },
  { name: "James Absalom", url: "https://www.linkedin.com/in/james-absalom-4619223b/" },
  { name: "Emily Emiko Miyakawa", url: "https://www.linkedin.com/in/emilyemikomiyakawa/" },
  { name: "Nisar Qureshi", url: "https://www.linkedin.com/in/nisar-qureshi-35109124/" },
  { name: "Unmesha Pentakota", url: "https://www.linkedin.com/in/unmeshap/" },
  { name: "Adriana Orelhana", url: "https://www.linkedin.com/in/adriana-orelhana/" },
  { name: "Stefani Neves", url: "https://www.linkedin.com/in/stefani-neves/" },
  { name: "Duda Riobo", url: "https://www.linkedin.com/in/dudariobo/" },
  { name: "Renata Fabrini", url: "https://www.linkedin.com/in/renata-fabrini/" },
  { name: "Gabriela Rezende Amorim", url: "https://www.linkedin.com/in/gabrielarezendeamorim/" },
  { name: "Camila Soares Ferreira", url: "https://www.linkedin.com/in/camila-soares-ferreira-43b9a11ba/" },
  { name: "Fernanda Bonutti Ribeiro", url: "https://www.linkedin.com/in/fernanda-bonutti-ribeiro/" },
  { name: "Ingrid Caroline", url: "https://www.linkedin.com/in/ingridcarolinedasilva/" },
  { name: "Rafael Rodrigues", url: "https://www.linkedin.com/in/rafael-rodrigues-68555772/" },
  { name: "Andre Guerra", url: "https://www.linkedin.com/in/andre-guerra/" },
  { name: "Gabriela Machado D.", url: "https://www.linkedin.com/in/gabriela-machado-silveira/" },
  { name: "Emily Erculano", url: "https://www.linkedin.com/in/emily-erculano/" },
  { name: "Ricardo Du Pain", url: "https://www.linkedin.com/in/ricardo-du-pain-86019/" },
  { name: "Leonardo Koga", url: "https://www.linkedin.com/in/leonardokoga/" },
  { name: "Raquel Du Pain", url: "https://www.linkedin.com/in/raquel-du-pain/" },
  { name: "Mariana Jolis", url: "https://www.linkedin.com/in/marianajolis/" },
  { name: "Silvana Nardini Bock", url: "https://www.linkedin.com/in/silvana-nardini-bock-8905a8/" },
  { name: "Thiago Paiva", url: "https://www.linkedin.com/in/thiago-paiva-psico/" },
  { name: "Bianca Nunes de Andrade", url: "https://www.linkedin.com/in/bianca-nunes-de-andrade/" },
  { name: "Tais Carvalho", url: "https://www.linkedin.com/in/taisc/" },
  { name: "Jéssica Mottola", url: "https://www.linkedin.com/in/jessicamottola/" },
  { name: "Yukiko Takaishi", url: "https://www.linkedin.com/in/yukikotakaishi/" },
  { name: "Camila Sgavioli", url: "https://www.linkedin.com/in/camilasgavioli/" },
  { name: "Rosana Souza", url: "https://www.linkedin.com/in/rosana-souza-a2660816/" },
  { name: "Rita de Cássia Ferreira", url: "https://www.linkedin.com/in/rita-de-c%C3%A1ssia-ferreira/" },
  { name: "Bernardo Mascarenhas", url: "https://www.linkedin.com/in/bernardo-mascarenhas-5a919755/" },
  { name: "Thayanie (Thay) Ujino", url: "https://www.linkedin.com/in/thayanie-ujino-6675761/" },
  { name: "Luisa Gentil Blandy", url: "https://www.linkedin.com/in/luisa-gentil-blandy-0212759/" },
  { name: "Anderson Schemberg", url: "https://www.linkedin.com/in/anderson-schemberg-05280156/" },
  { name: "Katia Nekandaris", url: "https://www.linkedin.com/in/katianekandaris/" },
  { name: "Jéssica Freire", url: "https://www.linkedin.com/in/jessicamoraesfreire/" },
  { name: "Marcela Mendonça", url: "https://www.linkedin.com/in/marcela-mendon%C3%A7a-7b99647/" },
  { name: "Mariana Bento", url: "https://www.linkedin.com/in/mariana-bento-29168a46/" },
  { name: "Renato Bagnolesi", url: "https://www.linkedin.com/in/renato-bagnolesi-616389/" },
  { name: "Diego Lopes", url: "https://www.linkedin.com/in/diegoglopes/" },
  { name: "Débora Rangel Celeti", url: "https://www.linkedin.com/in/deboraceleti/" },
  { name: "Lucas Ribas Wilson", url: "https://www.linkedin.com/in/lucasr1/" },
  { name: "Lorena Souza", url: "https://www.linkedin.com/in/lorena-souza-1204/" },
  { name: "Thassiane Soares", url: "https://www.linkedin.com/in/thassiane-soares-bb394665/" },
  { name: "Marcia Gavron", url: "https://www.linkedin.com/in/marcia-gavron-552a501a/" },
  { name: "Beatriz Sairafi", url: "https://www.linkedin.com/in/beatrizsairafiheinemann/" },
  { name: "Fernanda Amaral", url: "https://www.linkedin.com/in/fernanda-amaral-20b9a0104/" },
  { name: "Ana Gabriella Lago", url: "https://www.linkedin.com/in/ana-gabriella-lago-91070066/" },
  { name: "Ana Carolina Zanon", url: "https://www.linkedin.com/in/ana-carolina-zanon-64209722/" },
  { name: "Leonardo Massuda", url: "https://www.linkedin.com/in/leonardomassuda/" },
  { name: "Marina Ferreira Perez", url: "https://www.linkedin.com/in/marina-ferreira-perez-06730225/" },
  { name: "Pedro Freitas", url: "https://www.linkedin.com/in/freitaspedro/" },
  { name: "Laura Tompson", url: "https://www.linkedin.com/in/laura-tompson-27557556/" },
  { name: "Miguel Monzu", url: "https://www.linkedin.com/in/miguel-monzu-0b91735/" },
  { name: "Débora Mitsue Kovacs", url: "https://www.linkedin.com/in/deboramitsuekovacs/" },
  { name: "Fabiana Pita da Rocha Alqualo", url: "https://www.linkedin.com/in/fabiana-pita-da-rocha-alqualo-3aa07128/" },
  { name: "Emilyn Machado", url: "https://www.linkedin.com/in/emilyn-machado-a99b0a15a/" },
  { name: "Gabriela Cimorelli", url: "https://www.linkedin.com/in/gabriela-cimorelli-a77694161/" },
  { name: "Laís Lobato", url: "https://www.linkedin.com/in/lais-lobato/" },
  { name: "Alexandre Espinosa", url: "https://www.linkedin.com/in/ale-espinosa/" },
  { name: "Liana Guimarães", url: "https://www.linkedin.com/in/lianaguimar%C3%A3es/" },
  { name: "Caroline Badra", url: "https://www.linkedin.com/in/carolinebadra/" },
  { name: "Miriam Paoliello", url: "https://www.linkedin.com/in/miriampaoliello/" },
  { name: "Natalia Geron Dias de Carvalho", url: "https://www.linkedin.com/in/nataliagerondias/" },
  { name: "Fabio Medeiros", url: "https://www.linkedin.com/in/fabio-medeiros-6483b8/" },
  { name: "Rafael Savian Zanlorenzi", url: "https://www.linkedin.com/in/rafaelzanlorenzi/" },
  { name: "Carlos Guilherme Nosé", url: "https://www.linkedin.com/in/carlosguilherme/" },
  { name: "Asap Belo Horizonte", url: "https://www.linkedin.com/in/asap-belo-horizonte-b3044649/" },
  { name: "Rebecca Andrade", url: "https://www.linkedin.com/in/rebecca-andrade-a87ab310a/" },
  { name: "Silvana Loureiro", url: "https://www.linkedin.com/in/silvanaloureiro/" },
  { name: "Clayton Pedro", url: "https://www.linkedin.com/in/clayton-pedro/" },
  { name: "Erika Xavier Fava", url: "https://www.linkedin.com/in/erika-xavier-fava-0a318820/" },
  { name: "Stella Lazzuri", url: "https://www.linkedin.com/in/stella-lazzuri-05b598b4/" },
  { name: "Fernando Ladeira", url: "https://www.linkedin.com/in/fernandoladeirafernandes/" },
  { name: "Adaildo Vieira", url: "https://www.linkedin.com/in/adaildovieira/" },
  { name: "Raquel Patti", url: "https://www.linkedin.com/in/pattiraquel/" },
  { name: "Barbara Partezani Schneider", url: "https://www.linkedin.com/in/barbara-partezani-schneider-885a98216/" },
  { name: "Leticia Carvalho", url: "https://www.linkedin.com/in/leticiag-carvalho/" },
  { name: "Thiago Pinto", url: "https://www.linkedin.com/in/thiago-pinto-50601828/" },
  { name: "Cibele Castro", url: "https://www.linkedin.com/in/cibele-castro/" },
  { name: "Natália Yanazuky", url: "https://www.linkedin.com/in/nat%C3%A1lia-yanazuky-bb203b49/" },
  { name: "Fabiana Calixto", url: "https://www.linkedin.com/in/fabiana-calixto-a8271955/" },
  { name: "Fernanda Azzi", url: "https://www.linkedin.com/in/fernandaazzi/" },
  { name: "Juliane (Fesa-Sp)", url: "https://www.linkedin.com/in/juliane-fesa-sp-01299822/" },
  { name: "Fabiana Azevêdo", url: "https://www.linkedin.com/in/fabiana-azevedo/" },
  { name: "Guilherme Bittar", url: "https://www.linkedin.com/in/guilherme-bittar-801590b7/" },
  { name: "Millena Siqueira", url: "https://www.linkedin.com/in/millena-siqueira/" },
  { name: "Livia Miguel Antonio", url: "https://www.linkedin.com/in/livia-miguel-antonio-6114413/" },
  { name: "Luisa Matias", url: "https://www.linkedin.com/in/luisa-matias-66984ab6/" },
  { name: "Selma Fukushima", url: "https://www.linkedin.com/in/selma-fukushima-6781906/" },
  { name: "Cecília Toraci", url: "https://www.linkedin.com/in/cec%C3%ADlia-toraci-a5958b2/" },
  { name: "Tamyres Haluch Santos", url: "https://www.linkedin.com/in/tamyreshaluch/" },
  { name: "Hugo Lopes Montinho", url: "https://www.linkedin.com/in/hugo-lopes-montinho-a4440a48/" },
  { name: "Laura Mendes", url: "https://www.linkedin.com/in/laura-mendes-%F0%9F%8F%B3%EF%B8%8F%E2%80%8D%F0%9F%8C%88-aa5b6a173/" },
  { name: "Elisangela de Paula", url: "https://www.linkedin.com/in/elisangela-de-paula-494b92b2/" },
  { name: "Isabella Viana Trevizan", url: "https://www.linkedin.com/in/isatrevizan/" },
  { name: "Jaime Schlittler", url: "https://www.linkedin.com/in/jaimeschlittler/" },
  { name: "Patrícia Paiva, CFA", url: "https://www.linkedin.com/in/patr%C3%ADcia-paiva-cfa-b93403/" },
  { name: "Verena Lorenz", url: "https://www.linkedin.com/in/verenalorenz/" },
  { name: "Euri Cruz", url: "https://www.linkedin.com/in/euricruz/" },
  { name: "Alexandre Sabbag", url: "https://www.linkedin.com/in/alexandresabbag/" },
  { name: "Bianca Gonçalves", url: "https://www.linkedin.com/in/biancagoncalvesbg/" },
  { name: "Giancarlo Alcalai", url: "https://www.linkedin.com/in/giancarlo-alcalai-88087313/" },
  { name: "Francisco Cuesta", url: "https://www.linkedin.com/in/francisco-cuesta/" },
  { name: "Monica Tomita", url: "https://www.linkedin.com/in/monicatomitaalbino/" },
  { name: "Marcela Ordine Sia", url: "https://www.linkedin.com/in/marcela-ordine-sia-12b7186/" },
  { name: "Amelia Caetano", url: "https://www.linkedin.com/in/amelia-caetano-3026213/" },
  { name: "David Sion Turkie", url: "https://www.linkedin.com/in/davidsionturkie/" },
  { name: "Renata Gentil", url: "https://www.linkedin.com/in/renata-gentil-148b64b/" },
  { name: "Julio Bonrruquer Neto", url: "https://www.linkedin.com/in/juliob/" },
  { name: "Juliana - Motta", url: "https://www.linkedin.com/in/julianamotta/" },
  { name: "Débora Micchi Hila", url: "https://www.linkedin.com/in/deboravmicchihila/" },
  { name: "Adriana Martins Garcia", url: "https://www.linkedin.com/in/adriana-martins-garcia-2216639/" },
  { name: "Caccuri Executive Search", url: "https://www.linkedin.com/in/caccuri-executive-search-78a80932/" },
  { name: "Daniella Lopes Cançado", url: "https://www.linkedin.com/in/daniella-lopes-can%C3%A7ado-0656452a/" },
  { name: "Rebeca Prates Souza", url: "https://www.linkedin.com/in/rebeca-prates-souza/" },
  { name: "Daniel Rezende", url: "https://www.linkedin.com/in/danielrezendedesouza/" },
  { name: "Jessica Lima", url: "https://www.linkedin.com/in/jessica-lima-rh/" },
  { name: "Adriana Prates", url: "https://www.linkedin.com/in/adriana-prates-7bb40111/" },
  { name: "Irani Feliciano", url: "https://www.linkedin.com/in/irani-feliciano-78273574/" },
  { name: "Mariele Zapula", url: "https://www.linkedin.com/in/mariele-gon%C3%A7alves-oliveira-zapula/" },
  { name: "Marina Loureiro", url: "https://www.linkedin.com/in/marina-loureiro-2000/" },
  { name: "Brenda Martins Veronezi", url: "https://www.linkedin.com/in/brendamartinss/" },
  { name: "marcelo castelleti castelleti", url: "https://www.linkedin.com/in/marcelo-castelleti-castelleti-670b8338/" },
  { name: "Maria Helena Scatolino", url: "https://www.linkedin.com/in/maria-helena-scatolino-274a8712b/" },
  { name: "Luiz Gonzaga Leal", url: "https://www.linkedin.com/in/luiz-leal-/" },
  { name: "George H C Millard", url: "https://www.linkedin.com/in/georgemillard/" },
  { name: "Aurea Rovaron", url: "https://www.linkedin.com/in/aurea-rovaron-36246642/" },
  { name: "Danute Gardziulis Carneiro", url: "https://www.linkedin.com/in/danutegardziulis/" },
  { name: "Denise Fileti Barreto", url: "https://www.linkedin.com/in/denisebarreto/" },
  { name: "Paula Garcia", url: "https://www.linkedin.com/in/paula-garcia-508b35/" },
  { name: "Amanda Lázaro", url: "https://www.linkedin.com/in/amandalazaro/" },
  { name: "Inêz Zanoni", url: "https://www.linkedin.com/in/inezzanoni/" },
  { name: "Gabriela Altafim", url: "https://www.linkedin.com/in/gabriela-altafim/" },
  { name: "Fernanda Siqueira", url: "https://www.linkedin.com/in/fernandasiqueira/" },
  { name: "Thifany Madrid Lopes", url: "https://www.linkedin.com/in/thifanymadrid/" },
  { name: "Thais Monteiro Marcolino", url: "https://www.linkedin.com/in/thaismonteiro1/" },
  { name: "Tabatha Fender", url: "https://www.linkedin.com/in/tabatha-fender-902b8194/" },
  { name: "Bárbara Muniz", url: "https://www.linkedin.com/in/barbarabrmuniz/" },
  { name: "Isabella Cabrini", url: "https://www.linkedin.com/in/isabellacabrini/" },
  { name: "Fernanda Degani", url: "https://www.linkedin.com/in/fernanda-degani-54aa777b/" },
  { name: "Helena Bezerra", url: "https://www.linkedin.com/in/helena-bezerra-90a59a238/" },
  { name: "Juliana Gualter", url: "https://www.linkedin.com/in/juliana-gualter/" },
  { name: "Júlia Zupi", url: "https://www.linkedin.com/in/juliazupi/" },
  { name: "Verena Lorenz", url: "https://www.linkedin.com/in/carina-sampaio-a5211722/" },
  { name: "Aline Kelly", url: "https://www.linkedin.com/in/aline-kelly-ba756440/" },
  { name: "Maria Eduarda Cordeiro", url: "https://www.linkedin.com/in/mariaeduardadossantoscordeiro/" },
  { name: "Thiago Mariano", url: "https://www.linkedin.com/in/marianothiago/" },
  { name: "Beatriz Verissimo", url: "https://www.linkedin.com/in/beatriz-verissimo/" },
  { name: "Vanessa Zehetmeyer", url: "https://www.linkedin.com/in/vanessazehetmeyer/" },
  { name: "Maria Emilia (Mila) Azevedo", url: "https://www.linkedin.com/in/mariaemiliaazevedo/" },
  { name: "Luis Fernando Martins", url: "https://www.linkedin.com/in/luisfmsilva/" },
  { name: "Raphael Falcão", url: "https://www.linkedin.com/in/raphaelfalcao/" },
  { name: "Carlos Kazuaki", url: "https://www.linkedin.com/in/carlos-kazuaki-709765150/" },
  { name: "Alissa Negri Madjarov Nobrega", url: "https://www.linkedin.com/in/alissa-negri-madjarov-nobrega-b800aa137/" },
  { name: "Thais Tiemi Seguchi", url: "https://www.linkedin.com/in/tseguchi/" },
  { name: "Leticia Longhi", url: "https://www.linkedin.com/in/leticia-longhi-893636194/" },
  { name: "Amanda P.", url: "https://www.linkedin.com/in/amanda-p-871953158/" },
  { name: "Thais Mariz", url: "https://www.linkedin.com/in/thaismariz/" },
  { name: "Mariana Nicodemo", url: "https://www.linkedin.com/in/mariana-nicodemo/" },
  { name: "Amanda Wasong", url: "https://www.linkedin.com/in/adwasong/" },
  { name: "Ana Paula Assunção Filgueiras", url: "https://www.linkedin.com/in/apassuncao/" },
  { name: "Marcelo Leite", url: "https://www.linkedin.com/in/hrmarceloleite/" },
  { name: "Isabela Ignacio", url: "https://www.linkedin.com/in/isabela-ignacio/" },
  { name: "Marcelo Conteçote", url: "https://www.linkedin.com/in/marcelo-contecote/" },
  { name: "Marcos Macedo", url: "https://www.linkedin.com/in/marcos-macedo-6b74a3/" },
  { name: "Carla Camargo", url: "https://www.linkedin.com/in/carla-camargo-/" },
  { name: "Pâmela Leite de Oliveira", url: "https://www.linkedin.com/in/p%C3%A2mela-leite-de-oliveira-867258112/" },
  { name: "Marcelo Lavall", url: "https://www.linkedin.com/in/marcelo-lavall-8b150b5/" },
  { name: "Alessandra Milani", url: "https://www.linkedin.com/in/alessandramilani2024/" },
  { name: "Gabriel Gusmão", url: "https://www.linkedin.com/in/gabrielgusmao/" },
  { name: "Luciana Assad", url: "https://www.linkedin.com/in/luciana-assad/" },
  { name: "Patrícia Xavier", url: "https://www.linkedin.com/in/patr%C3%ADcia-xavier-61a33a23/" },
  { name: "Marina Ramos", url: "https://www.linkedin.com/in/marinanramos/" },
  { name: "Vitor Andrade", url: "https://www.linkedin.com/in/vandrade-alves/" },
  { name: "Carlos Eduardo A. de Barros", url: "https://www.linkedin.com/in/carloseabarros/" },
  { name: "Karine de Freitas Hannemann", url: "https://www.linkedin.com/in/karinefhannemann/" },
  { name: "Carolina Terribas", url: "https://www.linkedin.com/in/carolina-terribas-2a8b782a2/" },
  { name: "Camila Rago", url: "https://www.linkedin.com/in/camila-rago-10b093149/" },
  { name: "Lea Federmann", url: "https://www.linkedin.com/in/lea-federmann-25bb715/" },
  { name: "Paula Guerra", url: "https://www.linkedin.com/in/paula-guerra-b180662b/" },
  { name: "Juliana Belli", url: "https://www.linkedin.com/in/juliana-zbelli/" },
  { name: "Luís Arrobas", url: "https://www.linkedin.com/in/arrobas/" },
  { name: "Fabiana Cotrim", url: "https://www.linkedin.com/in/fabiana-cotrim-4831695/" },
  { name: "Samir Couri", url: "https://www.linkedin.com/in/samir-couri/" },
  { name: "Rafaela Ramos", url: "https://www.linkedin.com/in/rafaelasramos/" },
  { name: "João Marco (Adamo Beltrão) Frederico", url: "https://www.linkedin.com/in/joaomarco/" },
  { name: "Ricardo Amatto", url: "https://www.linkedin.com/in/ricardoamatto/" },
  { name: "Guilherme (Gui) Maciel", url: "https://www.linkedin.com/in/gmaciel10/" },
  { name: "Gisele Diogo Vieira", url: "https://www.linkedin.com/in/gisele-diogo-vieira-802249119/" },
  { name: "Amanda Nader", url: "https://www.linkedin.com/in/amandanader/" },
  { name: "Luciana Damasio", url: "https://www.linkedin.com/in/luciana-damasio-saldanha/" },
  { name: "Horacio Saccoman", url: "https://www.linkedin.com/in/horacio-saccoman-1428495/" },
  { name: "Jucila Misseno", url: "https://www.linkedin.com/in/jucila-misseno/" },
  { name: "Ieda de Paula", url: "https://www.linkedin.com/in/ieda-de-paula-hr-consultancy/" },
  { name: "Mariangela Schoenacker", url: "https://www.linkedin.com/in/mariangela-schoenacker/" },
  { name: "Cristina Fortes", url: "https://www.linkedin.com/in/cristina-fortes-21067734/" },
  { name: "Caroline Reis, PCC ICF", url: "https://www.linkedin.com/in/carolinereis/" },
  { name: "Alexandre Moraes", url: "https://www.linkedin.com/in/alexandre-moraes-consultor/" },
  { name: "Denise Sztokman, M.Sc", url: "https://www.linkedin.com/in/denise-paes-sztokman/" },
  { name: "Simonne Noronha", url: "https://www.linkedin.com/in/simonne-noronha/" },
  { name: "Francisco Penteado Neto,Coach", url: "https://www.linkedin.com/in/franciscopenteadocoach/" },
  { name: "José Augusto Figueiredo", url: "https://www.linkedin.com/in/joseaugustofigueiredo/" },
  { name: "Richard Dubini", url: "https://www.linkedin.com/in/richarddubini/" },
  { name: "Giovanni Custodio", url: "https://www.linkedin.com/in/giovanni-custodio/" },
  { name: "Fernando Morais", url: "https://www.linkedin.com/in/fernandomorais1/" },
  { name: "Felipe Luiz Rodrigues", url: "https://www.linkedin.com/in/felipe-luiz-rodrigues-/" },
  { name: "Tatiana Sharmaine", url: "https://www.linkedin.com/in/tatiana-sharmaine/" },
  { name: "Gabriela Altafim", url: "https://www.linkedin.com/in/gabriela-altafim/" },
  { name: "Patricia Serra, MBA, PCC", url: "https://www.linkedin.com/in/patriciaserra/" },
  { name: "Suzana Kertesz", url: "https://www.linkedin.com/in/suzana-kertesz/" },
  { name: "Marcia Amorim", url: "https://www.linkedin.com/in/m-amorim/" },
  { name: "Daniel Stolses", url: "https://www.linkedin.com/in/danielstolses/" },
  { name: "Lorena Der Hovannessian Quinan", url: "https://www.linkedin.com/in/lorenaquinan/" },
  { name: "Erica Figueiredo Gonçalves", url: "https://www.linkedin.com/in/ericafg/" },
  { name: "Katia Gaspar", url: "https://www.linkedin.com/in/katiagaspar/" },
  { name: "Vera Pellegrino", url: "https://www.linkedin.com/in/vera-pellegrino-0867435/" },
  { name: "Alicia R. Goldsztejn Morata", url: "https://www.linkedin.com/in/aliciagoldzstejn/" },
  { name: "Cecília Marcos", url: "https://www.linkedin.com/in/ceciliamarcos/" },
  { name: "Ana Paula Martim", url: "https://www.linkedin.com/in/anapaula-martim/" },
  { name: "Renata Muramatsu", url: "https://www.linkedin.com/in/renata-muramatsu/" },
  { name: "BEATRIZ BORGES (BABI)", url: "https://www.linkedin.com/in/beatrizborges-babi/" },
  { name: "Guilherme Chelles", url: "https://www.linkedin.com/in/guilhermechelles/" },
  { name: "Mabel Minto", url: "https://www.linkedin.com/in/mabel-minto-4b1226a/" },
  { name: "Beatriz Marimon", url: "https://www.linkedin.com/in/beatrizmarimon/" },
  { name: "Mariana Lobato", url: "https://www.linkedin.com/in/marianalobato/" },
  { name: "Carmem Rocha", url: "https://www.linkedin.com/in/carmemrocha/" },
  { name: "Arlete Almeida", url: "https://www.linkedin.com/in/arletealmeida/" },
  { name: "Rita Elias", url: "https://www.linkedin.com/in/ritacassiaelias/" },
  { name: "Rogerio Sêpa", url: "https://www.linkedin.com/in/rogeriosepa/" },
  { name: "Ana Paula Cramez", url: "https://www.linkedin.com/in/anapaulacramez/" },
  { name: "Marina Vergili", url: "https://www.linkedin.com/in/marina-vergili/" },
  { name: "Vera Pellegrino", url: "https://www.linkedin.com/in/silvanaloureiro/" },
  { name: "Vera Pellegrino ", url: "https://www.linkedin.com/in/maraturolla/" },
  { name: "Marisa Bueno", url: "https://www.linkedin.com/in/marisabueno09/" },
  { name: "Fernando Tatit", url: "https://www.linkedin.com/in/fernandomltatit/" },
  { name: "Luiza Figueiredo", url: "https://www.linkedin.com/in/luizarfigueiredo/" },
  { name: "Glauter Jannuzzi", url: "https://www.linkedin.com/in/jannuzzi/" },
  { name: "Wilson Trevisan", url: "https://www.linkedin.com/in/wilsontrevisan/" },
  { name: "Andrea Pirani Puglisi", url: "https://www.linkedin.com/in/andrea-pirani-puglisi/" },
  { name: "Heloisa Scarantino", url: "https://www.linkedin.com/in/heloisascarantino/" },
  { name: "Paula Violante", url: "https://www.linkedin.com/in/paulaabcviolante/" },
  { name: "Sabrina Monaco, CEO/ICF/PCC", url: "https://www.linkedin.com/in/sabrinamonaco-coach/" },
  { name: "Deborah Piersanti Carceles", url: "https://www.linkedin.com/in/deborahcarceles/" },
  { name: "Helena Tundisi", url: "https://www.linkedin.com/in/helenatundisi/" },
  { name: "Viviane Santos", url: "https://www.linkedin.com/in/viviane-santos-headhunter/" },
  { name: "Pedro Affonso Ferreira", url: "https://www.linkedin.com/in/pedro-affonso-ferreira/" },
  { name: "Marcos da Cunha Ribeiro", url: "https://www.linkedin.com/in/marcos-da-cunha-ribeiro-768295/" },
  { name: "Thais Calixto", url: "https://www.linkedin.com/in/thais-calixto-bb9687123/" },
  { name: "Fernanda Abud Palma", url: "https://www.linkedin.com/in/fernandaabudpalma/" },
  { name: "Márcia Teixeira", url: "https://www.linkedin.com/in/marciateixeira-headhunter/" },
  { name: "Rosana Mezzetti Cruz", url: "https://www.linkedin.com/in/rosanacruz/" },
  { name: "Leonardo Nantes", url: "https://www.linkedin.com/in/leonardonantes/" },
  { name: "Beth Barros", url: "https://www.linkedin.com/in/bethbarros/" },
  { name: "Cecile Harrison", url: "https://www.linkedin.com/in/cecileharrison/" },
  { name: "Emile Machado", url: "https://www.linkedin.com/in/emilemachado/" },
  { name: "Juliana Giacomini", url: "https://www.linkedin.com/in/juliana-ariel-giacomini-neckel/" },
  { name: "Denise Fanini Leite", url: "https://www.linkedin.com/in/denisefaninileite/" },
  { name: "Claudia Maltese", url: "https://www.linkedin.com/in/claudiamaltese/" },
  { name: "Andrea Guerra", url: "https://www.linkedin.com/in/andrea-guerra-2bab501a/" },
  { name: "Priscyla Furlan", url: "https://www.linkedin.com/in/priscyla-furlan/" },
  { name: "Tatiana Fiore", url: "https://www.linkedin.com/in/tatiana-fiore-mkt2020/" },
  { name: "Carmelina Nickel", url: "https://www.linkedin.com/in/carmelina-nickel/" },
  { name: "Lu Andrade", url: "https://www.linkedin.com/in/luandrade/" },
  { name: "Cassio Azevedo", url: "https://www.linkedin.com/in/cassioazevedo/" },
  { name: "Milene Lopes Schiavo", url: "https://www.linkedin.com/in/mileneschiavo/" },
  { name: "Ana Cristina Casagrande", url: "https://www.linkedin.com/in/ana-cristina-casagrande-1b986526/" },
  { name: "Letícia Mello", url: "https://www.linkedin.com/in/leticiamellom/" },
  { name: "Margareth Columa", url: "https://www.linkedin.com/in/margareth-columa-b513551/" },
  { name: "Bruno Scacalossi", url: "https://www.linkedin.com/in/brunoscacalossi/" },
  { name: "Claudia Rocha dos Santos Pereira", url: "https://www.linkedin.com/in/claudiarochasp/" },
  { name: "Sharon Falcão", url: "https://www.linkedin.com/in/sharon-falcao-060ab89/" },
  { name: "Renata Carneiro", url: "https://www.linkedin.com/in/carneirorenats/" },
  { name: "Simone Trewikowski", url: "https://www.linkedin.com/in/simonetrewikowski/" },
  { name: "Mônica Schmidt", url: "https://www.linkedin.com/in/mschmidt3/" },
  { name: "Sumaia Miguel", url: "https://www.linkedin.com/in/sumaia/" },
  { name: "Fátima Castilho", url: "https://www.linkedin.com/in/fatimacastilho/" },
  { name: "Flávia Feitosa", url: "https://www.linkedin.com/in/flaviafeitosa/" },
  { name: "Alysson Vidiello", url: "https://www.linkedin.com/in/alyssonvidiello/" },
  { name: "Francine F Fiorese", url: "https://www.linkedin.com/in/francinefiorese/" },
  { name: "Antonio Carlos Fernandes Mendonca", url: "https://www.linkedin.com/in/antonio-carlos-fernandes-mendonca-223b186/" },
  { name: "Marcelo Tawil", url: "https://www.linkedin.com/in/marcelotawil/" },
  { name: "Cristiane Mazotto", url: "https://www.linkedin.com/in/cristianemazotto/" },
  { name: "Clarice Strauss", url: "https://www.linkedin.com/in/clarice-strauss-b6134924/" },
  { name: "Edson Marcelino", url: "https://www.linkedin.com/in/coach-edson-marcelino/" },
  { name: "Bruno Andrade", url: "https://www.linkedin.com/in/bruno-andrade5000/" },
  { name: "Jaqueline Gumm", url: "https://www.linkedin.com/in/jaquelinegumm/" },
  { name: "Carla Campos, HCMBOK® HCMP", url: "https://www.linkedin.com/in/carlacrcampos/" },
  { name: "Vania Helena Della Negra", url: "https://www.linkedin.com/in/vania-helena-della-negra/" },
  { name: "Emerson Pieri", url: "https://www.linkedin.com/in/emmobrasil/" },
  { name: "Liliane Seripierri", url: "https://www.linkedin.com/in/liliane-seripierri/" },
  { name: "Cristiane Oliver", url: "https://www.linkedin.com/in/cristianeoliver/" },
  { name: "Maria Lucia Giacomazzi", url: "https://www.linkedin.com/in/malugiacomazzi/" },
  { name: "Patricia Azeredo Paniquar", url: "https://www.linkedin.com/in/patriciapaniquar/" },
  { name: "Adriana Albuquerque", url: "https://www.linkedin.com/in/adrianaalbuquerque/" },
  { name: "Roberto \"Bob\" H.", url: "https://www.linkedin.com/in/robertobobhirsch/" },
  { name: "ARMANDO ASAMI URAZAKI", url: "https://www.linkedin.com/in/armando-asami-urazaki/" },
  { name: "Andréa Mauricio, MSc", url: "https://www.linkedin.com/in/andreamauricio/" },
  { name: "Isabel Pires", url: "https://www.linkedin.com/in/isabel-pires-ela-she-ella-b0763b43/" },
  { name: "Rodrigo Videira", url: "https://www.linkedin.com/in/rodrigo-videira-51519425/" },
  { name: "Daiana Foliatti", url: "https://www.linkedin.com/in/daianafoliatti/" },
  { name: "Gabriela Pizarro Cardozo", url: "https://www.linkedin.com/in/gabrielapizarro/" },
  { name: "Lucas Toledo", url: "https://www.linkedin.com/in/lucastoledo/" },
  { name: "Nícolas Ferro", url: "https://www.linkedin.com/in/nicolas-ferro/" },
  { name: "Camila Spicciati Margini", url: "https://www.linkedin.com/in/camila-spicciati-margini-729208203/" },
  { name: "Luana Castro", url: "https://www.linkedin.com/in/luana-castro-56b9b255/" },
  { name: "Emily Policeno", url: "https://www.linkedin.com/in/emily-policeno/" },
  { name: "Daniela Toledo", url: "https://www.linkedin.com/in/toledodaniela/" },
  { name: "Rose Pereira", url: "https://www.linkedin.com/in/rosecpereira/" },
  { name: "Thiago Pavam Ezequiel", url: "https://www.linkedin.com/in/thiago-pavam-ezequiel-21b469162/" },
  { name: "Gustavo Barbosa", url: "https://www.linkedin.com/in/gustavo-barbosa-13866658/" },
  { name: "Julia Riela", url: "https://www.linkedin.com/in/juliariela/" },
  { name: "Pedro Roméro", url: "https://www.linkedin.com/in/pedrorom%C3%A9ro/" },
  { name: "Ana Borges", url: "https://www.linkedin.com/in/ana-borges-13519929/" },
  { name: "Fernanda Gomes Garcia", url: "https://www.linkedin.com/in/fernanda-gomes-garcia-a225499/" },
  { name: "Laura Farsoni", url: "https://www.linkedin.com/in/laura-farsoni-44b2ba24/" },
  { name: "Ricardo Basaglia", url: "https://www.linkedin.com/in/basaglia/" },
  { name: "Danielle Marin", url: "https://www.linkedin.com/in/danielle-marin-62308611/" },
  { name: "Genis Fidelis", url: "https://www.linkedin.com/in/genis-fidelis-a6a07939/" },
  { name: "Andréia Ferreira", url: "https://www.linkedin.com/in/andreiaferreira2307/" },
  { name: "Lucas Papa", url: "https://www.linkedin.com/in/lucas-papa-76607467/" },
  { name: "Bruno Parente", url: "https://www.linkedin.com/in/bpcdias/" },
  { name: "Fabio Lessa", url: "https://www.linkedin.com/in/fabio-lessa-133b3a8/" },
  { name: "Juliana Ribeiro", url: "https://www.linkedin.com/in/juliana-ribeiro-49a148b8/" },
  { name: "Stephanie Christine Jeronymo", url: "https://www.linkedin.com/in/stephanie-christine-jeronymo-a96b3ab5/" },
  { name: "Gabriel Bardi", url: "https://www.linkedin.com/in/gabrielbardi/" },
  { name: "Fernando Gomes", url: "https://www.linkedin.com/in/fernando-gomes-4bb55b/" },
  { name: "Tatiana Zeilmann", url: "https://www.linkedin.com/in/tatiana-zeilmann-89154a9/" },
  { name: "Bruna Pescuma", url: "https://www.linkedin.com/in/bruna-pescuma-472673106/" },
  { name: "Stephano Dedini", url: "https://www.linkedin.com/in/stephano-dedini-3459899a/" },
  { name: "Marina Brandão", url: "https://www.linkedin.com/in/marinabrandao1/" },
  { name: "Simone Cristina Baadert", url: "https://www.linkedin.com/in/simonecristinaf/" },
  { name: "Leticia Matczak", url: "https://www.linkedin.com/in/leticia-matczak-5310a9b6/" },
  { name: "Thales Tolesano", url: "https://www.linkedin.com/in/thales-tolesano/" },
  { name: "André Pasternak", url: "https://www.linkedin.com/in/andr%C3%A9-pasternak-b382816/" },
  { name: "Vivian Ferreira Neves", url: "https://www.linkedin.com/in/vivian-ferreira-neves-33b44227/" },
  { name: "Sergio Costantini", url: "https://www.linkedin.com/in/sergiocostantini/" },
  { name: "Eduardo Gianesi", url: "https://www.linkedin.com/in/eduardogianesi/" },
  { name: "Ademar Couto", url: "https://www.linkedin.com/in/ademarcouto/" },
  { name: "Daniela Mindlin Tessler", url: "https://www.linkedin.com/in/danielatessler/" },
  { name: "Lídia Aleixo", url: "https://www.linkedin.com/in/l%C3%ADdia-aleixo-495540155/" },
  { name: "Antonio Carlos Brito", url: "https://www.linkedin.com/in/antonio-carlos-brito-8b1141/" },
  { name: "Pedro Villares Heer", url: "https://www.linkedin.com/in/pheer/" },
  { name: "Luiz Wever", url: "https://www.linkedin.com/in/luiz-wever/" },
  { name: "Erika Nagy", url: "https://www.linkedin.com/in/erika-nagy-61665a2/" },
  { name: "Carolina Trench", url: "https://www.linkedin.com/in/carolina-trench-4918b961/" },
  { name: "Gabriela Pacheco de Freitas", url: "https://www.linkedin.com/in/gabriela-pacheco-de-freitas-3095a0186/" },
  { name: "Flavio Pestana", url: "https://www.linkedin.com/in/flavio-pestana-14469514/" },
  { name: "Luciana Azevedo", url: "https://www.linkedin.com/in/luciana-azevedo-554279/" },
  { name: "Marcus Vinicius Freire OLY", url: "https://www.linkedin.com/in/marcus-vinicius-freire-oly-3a5b8b111/" },
  { name: "Devaney Baccarin", url: "https://www.linkedin.com/in/devaney-baccarin-2422845/" },
  { name: "Carlos Rosa", url: "https://www.linkedin.com/in/carlos-francisco-da-rosa/" },
  { name: "Fabio Prado", url: "https://www.linkedin.com/in/fabio-prado-163176/" },
  { name: "Lurde Mylla Araujo", url: "https://www.linkedin.com/in/lurde-mylla-araujo-8076bb220/" },
  { name: "Fabricia (Fabs/Fabris) Lentini", url: "https://www.linkedin.com/in/fabricia-lentini-%F0%9F%8F%B3%EF%B8%8F%E2%80%8D%F0%9F%8C%88-65a182b2/" },
  { name: "Aline dos Santos", url: "https://www.linkedin.com/in/aline-dos-santos-08a32a9/" },
  { name: "Anna Luiza Osser", url: "https://www.linkedin.com/in/anna-luiza-osser-b13372/" },
  { name: "Carolina Sales", url: "https://www.linkedin.com/in/carolina-sales/" },
  { name: "Patricia Osser", url: "https://www.linkedin.com/in/patricia-osser-sales-1a7142/" },
  { name: "Celso Tomanik", url: "https://www.linkedin.com/in/celso-tomanik-114151/" },
  { name: "Nayara Navalon", url: "https://www.linkedin.com/in/nayaranavalon/" },
  { name: "Thierre Garcia", url: "https://www.linkedin.com/in/thierregarcia/" },
  { name: "Ana Carla Guimaraes", url: "https://www.linkedin.com/in/anacarlaguimaraes/" },
  { name: "Mariana Horno Netto", url: "https://www.linkedin.com/in/mariana-horno-netto-911260a/" },
  { name: "Luis Antonio Oliveira Jr.", url: "https://www.linkedin.com/in/luisantoniooliveirajr/" },
  { name: "Bruna Baragatti", url: "https://www.linkedin.com/in/bruna-baragatti-09bb0b20/" },
  { name: "Sarah Reynard Toro", url: "https://www.linkedin.com/in/sarah-reynard-sr01/" },
  { name: "Leonardo Berto", url: "https://www.linkedin.com/in/leonardo-berto-0b15aa20/" },
  { name: "Fernando Gielfi", url: "https://www.linkedin.com/in/fernandogielfi/" },
  { name: "Bruna Martins", url: "https://www.linkedin.com/in/bruna-lopes-martins/" },
  { name: "Mario Custodio", url: "https://www.linkedin.com/in/mario-custodio/" },
  { name: "Patrícia (Paty) S.", url: "https://www.linkedin.com/in/patriciasouzares/" },
  { name: "Lucas Nogueira", url: "https://www.linkedin.com/in/lucas-nogueira-5ba80216/" },
  { name: "Leonardo Merigue", url: "https://www.linkedin.com/in/leonardo-merigue-26183767/" },
  { name: "Marina Lima", url: "https://www.linkedin.com/in/marina-lima-3421a224/" },
  { name: "Karen Silva Bezerra", url: "https://www.linkedin.com/in/karensbezerra/" },
  { name: "Luciano Rodrigues Vitor", url: "https://www.linkedin.com/in/luciano-rodrigues-vitor/" },
  { name: "Alexandre Attauah", url: "https://www.linkedin.com/in/alexandre-attauah/" },
  { name: "Renan Sarmento", url: "https://www.linkedin.com/in/renan-sarmento-a1035626/" },
  { name: "Giulia Dias da Cunha", url: "https://www.linkedin.com/in/giuliadiasdacunha/" },
  { name: "Karine Azevedo", url: "https://www.linkedin.com/in/karine-azevedo/" },
  { name: "Daniel Brito F. Maciel", url: "https://www.linkedin.com/in/daniel-brito-f-maciel/" },
  { name: "Evelin Luise", url: "https://www.linkedin.com/in/evelin-luise-3553138/" },
  { name: "Alexandre Mendonca", url: "https://www.linkedin.com/in/alexandre-mendonca-aa686570/" },
  { name: "Cristiane Domingues", url: "https://www.linkedin.com/in/cristiane-domingues-consultora-sap-mm-gest%C3%A3o-de-chamados-ams-1a634816/" },
  { name: "Glauco Benatti", url: "https://www.linkedin.com/in/glaucobenatti/" },
  { name: "Marcela Esteves", url: "https://www.linkedin.com/in/marcelaesteves/" },
  { name: "Fabio N. Kaneko", url: "https://www.linkedin.com/in/fabio-n-kaneko-331ba242/" },
  { name: "Cibele Oliveira", url: "https://www.linkedin.com/in/cibele-oliveira-9514a1127/" },
  { name: "Natália Peres", url: "https://www.linkedin.com/in/natalia-peres-soares/" },
  { name: "Débora Ribeiro", url: "https://www.linkedin.com/in/deborarbr/" },
  { name: "Lucia Taveira", url: "https://www.linkedin.com/in/luciataveira/" },
  { name: "Lucas Pinto", url: "https://www.linkedin.com/in/lpintoreis/" },
  { name: "Gabriel Tedeschi", url: "https://www.linkedin.com/in/gabriel-tedeschi-67621096/" },
  { name: "Thiago Pegaz", url: "https://www.linkedin.com/in/thiago-pegaz/" },
  { name: "Caio Rodrigues", url: "https://www.linkedin.com/in/caio-mcrodrigues/" },
  { name: "Aya Yokoyama", url: "https://www.linkedin.com/in/ayatakahashiyokoyama/" },
  { name: "Richard Townsend", url: "https://www.linkedin.com/in/richardtownsendrobertwalters/" },
  { name: "Yasmin Vasconcelos", url: "https://www.linkedin.com/in/yasminvsc/" },
  { name: "Sheyna Olliveira", url: "https://www.linkedin.com/in/sheyna-oliveira/" },
  { name: "Tatiana Chebat", url: "https://www.linkedin.com/in/tatianachebatwatanabe/" },
  { name: "Bruno F Martins", url: "https://www.linkedin.com/in/brunnomartins/" },
  { name: "Eduardo Utiyama", url: "https://www.linkedin.com/in/eduardo-utiyama-2a8a3b87/" },
  { name: "François-Pierre Puech", url: "https://www.linkedin.com/in/francoispierrepuech/" },
  { name: "Alex Campos", url: "https://www.linkedin.com/in/alexccampos/" },
  { name: "Geovana Ramos", url: "https://www.linkedin.com/in/geovana-ramos/" },
  { name: "Karoline Sousa", url: "https://www.linkedin.com/in/karolinesousa/" },
  { name: "Silvia Quirino", url: "https://www.linkedin.com/in/silviaquirino/" },
  { name: "Izabelli Alves", url: "https://www.linkedin.com/in/izabelli-alves/" },
  { name: "Izan García Fernández", url: "https://www.linkedin.com/in/izan-garc%C3%ADa-fern%C3%A1ndez-02327267/" },
  { name: "Pattra C.", url: "https://www.linkedin.com/in/pattra-chaipiyaphan/" },
  { name: "Maira Faria", url: "https://www.linkedin.com/in/mairafaria/" },
  { name: "Alexandre Campos", url: "https://www.linkedin.com/in/alexandre-campos-65b38833/" },
  { name: "María Pisonero", url: "https://www.linkedin.com/in/mariapisonero/" },
  { name: "Sarai Lucía Domínguez", url: "https://www.linkedin.com/in/saraidominguezmartinez/" },
  { name: "Grace Zhang", url: "https://www.linkedin.com/in/grace-zhang-7b7b0189/" },
  { name: "Joya Wang", url: "https://www.linkedin.com/in/joya-wang-34475b167/" },
  { name: "Viktorien van Loon", url: "https://www.linkedin.com/in/viktorienvanloon/" },
  { name: "Cezar Augusto", url: "https://www.linkedin.com/in/cezaraug/" },
  { name: "Alessandra Bellotto", url: "https://www.linkedin.com/in/alessandra-bellotto-196a524b/" },
  { name: "Luzia Souza Alves", url: "https://www.linkedin.com/in/luziaalves/" },
  { name: "Fernanda Somera", url: "https://www.linkedin.com/in/fernanda-somera-600a6326/" },
  { name: "Giovana Cervi", url: "https://www.linkedin.com/in/giovanacervi/" },
  { name: "Isabella Mussacredi Boscolo", url: "https://www.linkedin.com/in/isabella-mussacredi-boscolo-82670118b/" },
  { name: "Karina Brito", url: "https://www.linkedin.com/in/karina-brito-8130975/" },
  { name: "Jorge Kraljevic", url: "https://www.linkedin.com/in/jorge-kraljevic-34799b1/" },
  { name: "Rebeca Anafe", url: "https://www.linkedin.com/in/rebeca-anafe-055b4a106/" },
  { name: "Eline Kullock", url: "https://www.linkedin.com/in/eline-kullock/" },
  { name: "Carmen Miranda", url: "https://www.linkedin.com/in/carmenmiranda/" },
  { name: "Thorsten Otremba", url: "https://www.linkedin.com/in/thorstenotremba/" },
  { name: "Gilles Gaudefroy", url: "https://www.linkedin.com/in/gilles-gaudefroy/" },
  { name: "Simon Keim", url: "https://www.linkedin.com/in/simonkeim/" },
  { name: "Fernando Cunha", url: "https://www.linkedin.com/in/fernando-cunha-3736072/" },
  { name: "Gavin McCartney", url: "https://www.linkedin.com/in/gavin-mccartney-2a28a11/" },
  { name: "Christoph Leydolt", url: "https://www.linkedin.com/in/christoph-leydolt/" },
  { name: "Ken Nimitz", url: "https://www.linkedin.com/in/kennimitz/" },
  { name: "Melissa Petersen", url: "https://www.linkedin.com/in/melissa-petersen-a432b420/" },
  { name: "David Palmlund", url: "https://www.linkedin.com/in/david-palmlund-a01bb04/" },
  { name: "Marina Freeland", url: "https://www.linkedin.com/in/marina-freeland-aa22561/" },
  { name: "Carlos Ramalho", url: "https://www.linkedin.com/in/carlos-ramalho-4146887/" },
  { name: "Danielle Nokleby", url: "https://www.linkedin.com/in/danielle-nokleby-504b402/" },
  { name: "Denis Cho", url: "https://www.linkedin.com/in/denis-cho-4027011/" },
  { name: "Claudio Takao", url: "https://www.linkedin.com/in/claudio-takao-b62a915/" },
  { name: "Arlindo Marin", url: "https://www.linkedin.com/in/arlindo-marin-4b33061/" },
  { name: "Katia Navarrete", url: "https://www.linkedin.com/in/katia-navarrete-507332/" },
  { name: "Manuel Martins", url: "https://www.linkedin.com/in/manuel-martins-a349a58/" },
  { name: "Ruy Philip", url: "https://www.linkedin.com/in/ruy-philip-b977233/" },
  { name: "Luiz Calazans", url: "https://www.linkedin.com/in/luiz-calazans-760431a/" },
  { name: "Arlindo Marin", url: "https://www.linkedin.com/in/arlindo-marin-a81a64143/" },
  { name: "Luiz Felipe Calazans", url: "https://www.linkedin.com/in/luiz-felipe-calazans-45711a4/" },
  { name: "Fernando Denoye", url: "https://www.linkedin.com/in/fernando-denoye-9885685a/" },
  { name: "Edna Meira", url: "https://www.linkedin.com/in/edna-meira-2213b78/" },
  { name: "Cassia. Costa", url: "https://www.linkedin.com/in/cassia-costa-159646/" },
  { name: "Ana Miralla", url: "https://www.linkedin.com/in/ana-miralla-5125201/" },
  { name: "Larissa Zeni", url: "https://www.linkedin.com/in/larissa-zeni-a7359019/" },
  { name: "Edgard Xavier", url: "https://www.linkedin.com/in/edgard-xavier-b1b27921/" },
  { name: "Valeria Fernandes Matsuoka Ribeiro", url: "https://www.linkedin.com/in/valeria-fernandes-matsuoka-ribeiro-58aa743/" },
  { name: "Juliana Camargo", url: "https://www.linkedin.com/in/juliana-camargo-2191449/" },
  { name: "Tomás Grimaldi", url: "https://www.linkedin.com/in/tomasgrimaldi/" },
  { name: "José Carlos (Joey) Hassan Suárez", url: "https://www.linkedin.com/in/jchassansuarez/" },
  { name: "Sergio Bunin", url: "https://www.linkedin.com/in/sergiobunin/" },
  { name: "Riki ZHANG", url: "https://www.linkedin.com/in/riki-zhang-10662014/" },
  { name: "Silvia Flores", url: "https://www.linkedin.com/in/silvia-flores-s%C3%A1nchez/" },
  { name: "Valeria Fernandes Matsuoka Ribeiro", url: "https://www.linkedin.com/in/lorenzo-zavala/" },
  { name: "Marsha Pearcy", url: "https://www.linkedin.com/in/marsha-pearcy-819566a/" },
  { name: "Lei Pang", url: "https://www.linkedin.com/in/volanslei/" },
  { name: "Aura Gómez", url: "https://www.linkedin.com/in/aura-gomez/" },
  { name: "Pedro Gasset de Leyva", url: "https://www.linkedin.com/in/pedro-gasset-de-leyva/" },
  { name: "Fernando de Zavala Carvajal", url: "https://www.linkedin.com/in/fernandozavalacarvajal/" },
  { name: "Iván Rodriguez Búa", url: "https://www.linkedin.com/in/ivanrodriguezbua/" },
  { name: "Ayushi Chandna", url: "https://www.linkedin.com/in/ayushi-chandna-5543a4100/" },
  { name: "Barry Kirkwood", url: "https://www.linkedin.com/in/barrykirkwood/" },
  { name: "Xianghui Fei", url: "https://www.linkedin.com/in/xianghui-fei-29a820182/" },
  { name: "Gabriel Matos", url: "https://www.linkedin.com/in/gabriel-matos-a204b4163/" },
  { name: "Josep Balaguer", url: "https://www.linkedin.com/in/josep-balaguer-3b7976161/" },
  { name: "Jessica (蒋娇娇) Jiang", url: "https://www.linkedin.com/in/jessica-jiang-96b498244/" },
  { name: "Dolores Esnaola", url: "https://www.linkedin.com/in/doloresesnaola/" },
  { name: "Camille (徐优优) Xu", url: "https://www.linkedin.com/in/camille-xu-b04b11190/" },
  { name: "leonor pablos", url: "https://www.linkedin.com/in/leonorpablos23/" },
  { name: "Peter Martin Schledde", url: "https://www.linkedin.com/in/peter-martin-schledde-58085548/" },
  { name: "Jorge Ramos de Haro", url: "https://www.linkedin.com/in/jorge-ramos-de-haro-52a111149/" },
  { name: "Lila Di Gioia", url: "https://www.linkedin.com/in/lila-di-gioia-b1b9a2220/" },
  { name: "Ricardo Zavala", url: "https://www.linkedin.com/in/ricardo-zavala-090735179/" },
  { name: "Adriana Alvarez Vargas", url: "https://www.linkedin.com/in/adriana-alvarez-vargas/" },
  { name: "Alejandra Gallego Gómez", url: "https://www.linkedin.com/in/alegallego/" },
  { name: "Antonio Joaquim Motta Carvalho", url: "https://www.linkedin.com/in/antonio-joaquim-motta-carvalho-4434642/" },
  { name: "Antonio Motta", url: "https://www.linkedin.com/in/antonio-motta-b0272a1b/" },
  { name: "Luciano Carbonari", url: "https://www.linkedin.com/in/luciano-carbonari-82ab451/" },
  { name: "Eugene Walter Trenghouse", url: "https://www.linkedin.com/in/eugene-walter-trenghouse-956624aa/" },
  { name: "Luis Cabrera", url: "https://www.linkedin.com/in/luis-cabrera-36029a/" },
  { name: "Cilene Saraiva", url: "https://www.linkedin.com/in/cilene-saraiva-58520a24/" },
  { name: "Edna Gomes Brito", url: "https://www.linkedin.com/in/edna-gomes-brito-379179b0/" },
  { name: "Joel Carmo", url: "https://www.linkedin.com/in/joel-carmo-8239b82/" },
  { name: "Thomas Ubersfeld", url: "https://www.linkedin.com/in/thomas-ubersfeld-8b33993/" },
  { name: "Ana Carolina Saraiva", url: "https://www.linkedin.com/in/ana-carolina-saraiva-304b821/" },
  { name: "Ana Beatriz Dal Fabbro", url: "https://www.linkedin.com/in/ana-beatriz-dal-fabbro-777b75/" },
  { name: "Maria Tereza Garcia W", url: "https://www.linkedin.com/in/maria-tereza-garcia-w-1731aa37/" },
  { name: "Robert Wong", url: "https://www.linkedin.com/in/robert-wong-b360474/" },
  { name: "Alexandre Benedetti", url: "https://www.linkedin.com/in/alexandrebenedetti/" },
  { name: "Gabriel Adib Goulardins", url: "https://www.linkedin.com/in/gabriel-adib-goulardins-45763854/" },
  { name: "Isis Borge Sangiovan", url: "https://www.linkedin.com/in/isisborge/" },
  { name: "Gustavo Marques", url: "https://www.linkedin.com/in/gamsjr/" },
  { name: "Ester Pinheiro", url: "https://www.linkedin.com/in/esterpinheiro/" },
  { name: "Amanda Fernandes", url: "https://www.linkedin.com/in/amandapfernandes/" },
  { name: "Mariana Siqueira", url: "https://www.linkedin.com/in/mariana-siqueira-a6b859129/" },
  { name: "Daniela Cepeda", url: "https://www.linkedin.com/in/daniela-cepeda/" },
  { name: "Karolina da Mota Veloso", url: "https://www.linkedin.com/in/karolina-da-mota-veloso-a86abb207/" },
  { name: "Ricardo Casiuch", url: "https://www.linkedin.com/in/ricardocasiuch/" },
  { name: "Gabriella Snoeck", url: "https://www.linkedin.com/in/gabriellasnoeck/" },
  { name: "Christophe Dumont", url: "https://www.linkedin.com/in/christopherdumont/" },
  { name: "Patrick Fitzgerald", url: "https://www.linkedin.com/in/patrick-fitzgerald1/" },
  { name: "Natália Vieira", url: "https://www.linkedin.com/in/nataliavieiramagna/" },
  { name: "Moacyr Souza", url: "https://www.linkedin.com/in/moacyr-souza-25b582101/" },
  { name: "Marcela Tenenbaum", url: "https://www.linkedin.com/in/marcelatenenbaum/" },
  { name: "Patricia Munhoz", url: "https://www.linkedin.com/in/patricia-munhoz-1b7a7077/" },
  { name: "Luiz Roberto Alencar", url: "https://www.linkedin.com/in/luizalencar/" },
  { name: "MAGNA Search", url: "https://www.linkedin.com/in/magna-search-775b94190/" },
  { name: "Fernanda Soliani Pereira", url: "https://www.linkedin.com/in/fersoliani/" },
  { name: "Aline Abrahão Kästner", url: "https://www.linkedin.com/in/alinekastner/" },
  { name: "Gustavo Souza", url: "https://www.linkedin.com/in/gustavomagna/" },
  { name: "Rogerio Campos de Souza", url: "https://www.linkedin.com/in/rogerio-campos-de-souza-ba709531/" },
  { name: "Luis Eduardo Leal", url: "https://www.linkedin.com/in/luis-eduardo-leal/" },
  { name: "Leticia Reis", url: "https://www.linkedin.com/in/leticia-reis-a734a6249/" },
  { name: "Patrick Hollard", url: "https://www.linkedin.com/in/patrickhollard/" },
  { name: "Maíra Campos", url: "https://www.linkedin.com/in/ma%C3%ADra-campos-2091962a/" },
  { name: "Luis Felipe Lisboa", url: "https://www.linkedin.com/in/luis-felipe-lisboa-30287641/" },
  { name: "Samantha Molina", url: "https://www.linkedin.com/in/samantha-molina-846bb262/" },
  { name: "Lucas Ungaro", url: "https://www.linkedin.com/in/lucas-ungaro-280471aa/" },
  { name: "Bruna L.", url: "https://www.linkedin.com/in/bruna-l-4636a290/" },
  { name: "Guilherme Gonçalves", url: "https://www.linkedin.com/in/guilherme-gon%C3%A7alves/" },
  { name: "Lucas Oggiam", url: "https://www.linkedin.com/in/lucas-oggiam-2b26b837/" },
  { name: "João Paulo Cheregati Veras", url: "https://www.linkedin.com/in/jo%C3%A3o-paulo-cheregati-veras-483ba113a/" },
  { name: "Caio Liberatti", url: "https://www.linkedin.com/in/caioliberatti/" },
  { name: "Humberto Gazziero Wahrhaftig", url: "https://www.linkedin.com/in/humbertogw/" },
  { name: "Janaína Barussi", url: "https://www.linkedin.com/in/jana%C3%ADna-barussi-973a38153/" },
  { name: "Lenora P. Bonoldi Dutra", url: "https://www.linkedin.com/in/lenoradutrarh/" },
  { name: "Rodrigo Almeida", url: "https://www.linkedin.com/in/rodrigo-almeida-93150116/" },
  { name: "Thatiana Souza Dantas", url: "https://www.linkedin.com/in/thatiana-souza-dantas-702b931/" },
  { name: "Juliana França", url: "https://www.linkedin.com/in/julianafnfranca/" },
  { name: "Nina França", url: "https://www.linkedin.com/in/nina-fran%C3%A7a-57b07b3b/" },
  { name: "Iara Pinheiro", url: "https://www.linkedin.com/in/iara-pinheiro-411a074b/" },
  { name: "Gijs van Delft", url: "https://www.linkedin.com/in/gijsvandelft/" },
  { name: "Juliana Palermo", url: "https://www.linkedin.com/in/julianapalermo/" },
  { name: "Andressa Almeida", url: "https://www.linkedin.com/in/andressa-almeida-4b784343/" },
  { name: "Guilherme Koiyama", url: "https://www.linkedin.com/in/guikoy/" },
  { name: "Marcus Paulo Andrade", url: "https://www.linkedin.com/in/marcuspauloandrade/" },
  { name: "Victoria F Atherino Quintella", url: "https://www.linkedin.com/in/victoria-f-atherino-quintella-b559b582/" },
]

function HeadhuntersModal({
  open,
  onClose,
  title = "Headhunters",
}: {
  open: boolean
  onClose: () => void
  title?: string
}) {
  const [q, setQ] = useState("")

  useEffect(() => {
    if (!open) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose()
    }
    document.addEventListener("keydown", onKey)
    return () => document.removeEventListener("keydown", onKey)
  }, [open, onClose])

  const filtered = useMemo(() => {
    const t = q.trim().toLowerCase()
    if (!t) return HEADHUNTERS
    return HEADHUNTERS.filter(h => h.name.toLowerCase().includes(t))
  }, [q])

  if (!open) return null

  return (
    <div
      onClick={onClose}
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,.45)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10000,
        padding: 16,
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          width: "min(720px, 95vw)",
          maxHeight: "85vh",
          background: "#fff",
          borderRadius: 12,
          boxShadow: "0 12px 32px rgba(0,0,0,.2)",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", padding: "14px 16px", borderBottom: "1px solid #eee" }}>
          <h3 style={{ margin: 0, fontSize: 18, flex: 1 }}>{title}</h3>
          <button
            onClick={onClose}
            aria-label="Fechar"
            style={{
              border: "none",
              background: "transparent",
              fontSize: 20,
              lineHeight: 1,
              cursor: "pointer",
            }}
          >
            ×
          </button>
        </div>

        <div style={{ padding: "10px 16px", borderBottom: "1px solid #f2f2f2" }}>
          <input
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Buscar por nome…"
            style={{
              width: "100%",
              padding: "10px 12px",
              borderRadius: 8,
              border: "1px solid #ddd",
              outline: "none",
              fontSize: 14,
            }}
          />
        </div>

        <div style={{ overflowY: "auto", padding: 8 }}>
          {filtered.length === 0 ? (
            <div style={{ padding: 16, color: "#777", fontSize: 14 }}>Nenhum resultado.</div>
          ) : (
            <ul style={{ listStyle: "none", margin: 0, padding: 0 }}>
              {filtered.map((h) => (
                <li key={`${h.name}-${h.url}`}>
                  <a
                    href={h.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "space-between",
                      gap: 12,
                      padding: "10px 12px",
                      textDecoration: "none",
                      color: "#222",
                      borderBottom: "1px solid #f3f3f3",
                    }}
                  >
                    <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                      {h.name}
                    </span>
                    <span style={{ fontSize: 12, color: "#666" }}>Abrir ↗</span>
                  </a>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </div>
  )
}

export default HeadhuntersModal
